create TABLE IF NOT EXISTS activities(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
start_time DATETIME,
activity_desc VARCHAR(255),
activity_type ENUM('BIKING','HIKING', 'RUNNING', 'BASKETBALL')
);